os:
  - linux

language: go
go:
  - 1.15.x

services:
  - docker

addons:
  sonarcloud:
    organization: "open-cluster-management"
    token:
      secure: "gl+h/7tW7XCnlPgbWeVgXnbkY/ExVOGbXX5muiLuZxe1F8t8B4NEJRNyVAouIx930y3T9W4Ce0dAkVMOsQRJdsgAZACu0ikJs3mX1BSS4esO+SMcGbchq67mzIXGmisOZFkYKn1Euy1JmlF79NRYh0Z31h+jzeB+FjN2GDpuRKXRBOcJPltSYJySCyrouH5gdLAmpAVi+YG5unJRprBpeoM+1c2r1m5EwZqe0AonTCxy9eAkYKcotGEr4GTkXZufxQJTdgvzVEfXVbWrXz+AVSZboQhr/f38hYhFHyvebiGrSapzW52MiS91nJvskK6VflH+QYEyrMja3+yxsMW7ru9EJZEV9C018LCR9XWiutKacnrf/+rhLcBVCpdEKysa8Gg/fKzstwcBpF86UsptsyoIdM+8+ZzMS0tJzGoxDJWPUjoMcvKOoWKmZl1xun+BwiEywY890HhpnRB1mOU6Th+yn3ePuam3jrF0uYV4UHsV8kqsZjQouNVufLLzyFmJDhI6bVDlQnM+zNaqL4scDj6uk6nqOEnKiiy7KXZ54sU2xjWl/04l5zwErKB0x3ZhbzJwDNQwyvcy7rgC4nIW3WPsDzfG1zhdLRtzEsHyGwwsk2d11haORCEyhNamUwpLDPKlZyWhdAePPBszPsG1ZQ28rCLOsQHTFEX1tjVpXL4="

branches:
  only:
    - main
    - /^release-[0-9]+\..*$/

env:
  global:
    # Required
    - OS=linux
    - COMPONENT_TAG_EXTENSION="-${TRAVIS_COMMIT}"

    # Component Specific
    - COMPONENT_DEPLOY_COMMAND=${TRAVIS_BUILD_DIR}/build/deploy-to-cluster.sh
    - COMPONENT_INIT_COMMAND=${TRAVIS_BUILD_DIR}/build/install-dependencies.sh
    - COMPONENT_BUILD_COMMAND=${TRAVIS_BUILD_DIR}/build/build.sh
    - COMPONENT_UNIT_TEST_COMMAND=${TRAVIS_BUILD_DIR}/build/run-unit-tests.sh
    - COMPONENT_E2E_TEST_COMMAND=${TRAVIS_BUILD_DIR}/build/run-e2e-tests.sh
    - GO111MODULE=on

stages:
  - build
  - unit-test
  - test-e2e
  - release-ff
  - publish

before_script:
  # Bootstrap the build harness.
  - make
  # Set the image tag differently for PRs.
  - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export COMPONENT_TAG_EXTENSION="-PR${TRAVIS_PULL_REQUEST}-${TRAVIS_COMMIT}"; fi;
  # Use ssh to pull from private repos.
  - git config --global url."git@github.com:".insteadOf "https://github.com/"


jobs:
  include:
    - stage: build
      name: "Build the image and run unit tests"
      script:
        - make component/build
        - make component/push
    - stage: unit-test
      name: "Run unit tests"
      script:
        # Bootstrap the build harness, pull test image, and run unit tests.  
        - make copyright-check
        # - make component/pull 
        - make component/test/unit
        - make security/scans
        - make sonar/go  

    - stage: release-ff
      name: "Push commits to current release branch"
      if: type = push AND branch =~ /^main$/
      script:
        - make
        - make release-ff

    - stage: publish
      name: "Publish the image to quay with an official version/sha tag and publish entry to integration pipeline stage"
      if: type = push AND branch =~ /^release-[0-9]+\..*$/
      script:
        - make pipeline-manifest/update PIPELINE_MANIFEST_COMPONENT_SHA256=${TRAVIS_COMMIT} PIPELINE_MANIFEST_COMPONENT_REPO=${TRAVIS_REPO_SLUG} PIPELINE_MANIFEST_BRANCH=${TRAVIS_BRANCH}
