apiVersion: config.openshift.io/v1
kind: ClusterVersion
metadata:
  creationTimestamp: "2021-04-20T00:13:47Z"
  generation: 1
  managedFields:
  - apiVersion: config.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        .: {}
        f:channel: {}
        f:clusterID: {}
    manager: cluster-bootstrap
    operation: Update
    time: "2021-04-20T00:13:47Z"
  - apiVersion: config.openshift.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        .: {}
        f:availableUpdates: {}
        f:conditions: {}
        f:desired:
          .: {}
          f:channels: {}
          f:image: {}
          f:url: {}
          f:version: {}
        f:history: {}
        f:observedGeneration: {}
        f:versionHash: {}
    manager: cluster-version-operator
    operation: Update
    time: "2021-04-22T18:02:36Z"
  name: version
  resourceVersion: "1146008"
  selfLink: /apis/config.openshift.io/v1/clusterversions/version
  uid: 55ae1477-e5f1-43d5-b339-1b54051a476b
spec:
  channel: stable-4.7
  clusterID: 69365d80-c4ef-4999-8417-f14c8e2892c2
status:
  availableUpdates:
  - channels:
    - candidate-4.7
    - candidate-4.8
    - fast-4.7
    - stable-4.7
    image: quay.io/openshift-release-dev/ocp-release@sha256:2721145d62b8dbff8808cd7b12a8b24a81a8edad8f1078010f58c673f76bb419
    url: https://access.redhat.com/errata/RHBA-2021:1075
    version: 4.7.6
  - channels:
    - candidate-4.7
    - candidate-4.8
    - fast-4.7
    - stable-4.7
    image: quay.io/openshift-release-dev/ocp-release@sha256:93d68c88761c604448280d35367e7a253f1e05891a28d2ee4d99a4b474cf130f
    url: https://access.redhat.com/errata/RHBA-2021:0678
    version: 4.7.1
  - channels:
    - candidate-4.7
    - candidate-4.8
    - fast-4.7
    - stable-4.7
    image: quay.io/openshift-release-dev/ocp-release@sha256:aee8055875707962203197c4306e69b024bea1a44fa09ea2c2c621e8c5000794
    url: https://access.redhat.com/errata/RHBA-2021:1149
    version: 4.7.7
  - channels:
    - candidate-4.7
    - candidate-4.8
    - fast-4.7
    - stable-4.7
    image: quay.io/openshift-release-dev/ocp-release@sha256:83fca12e93240b503f88ec192be5ff0d6dfe750f81e8b5ef71af991337d7c584
    url: https://access.redhat.com/errata/RHBA-2021:0749
    version: 4.7.2
  - channels:
    - candidate-4.7
    - candidate-4.8
    - fast-4.7
    - stable-4.7
    image: quay.io/openshift-release-dev/ocp-release@sha256:edb08aaadf32f0b2e800f7e29e6f7a1b225211514401e92601ba94a971dec838
    url: https://access.redhat.com/errata/RHBA-2021:0821
    version: 4.7.3
  conditions:
  - lastTransitionTime: "2021-04-20T00:43:25Z"
    message: Done applying 4.7.0
    status: "True"
    type: Available
  - lastTransitionTime: "2021-04-22T18:19:06Z"
    status: "False"
    type: Failing
  - lastTransitionTime: "2021-04-20T00:43:25Z"
    message: Cluster version is 4.7.0
    status: "False"
    type: Progressing
  - lastTransitionTime: "2021-04-20T00:13:47Z"
    status: "True"
    type: RetrievedUpdates
  desired:
    channels:
    - candidate-4.7
    - candidate-4.8
    - fast-4.7
    - stable-4.7
    image: quay.io/openshift-release-dev/ocp-release@sha256:d74b1cfa81f8c9cc23336aee72d8ae9c9905e62c4874b071317a078c316f8a70
    url: https://access.redhat.com/errata/RHSA-2020:5633
    version: 4.7.0
  history:
  - completionTime: "2021-04-20T00:43:25Z"
    image: quay.io/openshift-release-dev/ocp-release@sha256:d74b1cfa81f8c9cc23336aee72d8ae9c9905e62c4874b071317a078c316f8a70
    startedTime: "2021-04-20T00:13:47Z"
    state: Completed
    verified: false
    version: 4.7.0
  observedGeneration: 1
  versionHash: sgAQIsA5EYs=
