# Source: insights-chart/templates/insights-role.yaml
# Copyright (c) 2021 Red Hat, Inc.
# Copyright Contributors to the Open Cluster Management project

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: open-cluster-management:insights-client:insights-client
  labels:
    app: insights
    chart: insights-chart-2.3.0
    component: insights-client
    release: insights-client
    heritage: Helm
rules:
- apiGroups:
  - wgpolicyk8s.io
  resources:
  - policyreports
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch   
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - managedclusters
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get 
  - list
  - watch
- apiGroups:
  - config.openshift.io
  resources:
  - clusterversions
  verbs:
  - list
  - get
  - watch
